apiVersion: apps/v1
kind: Deployment
metadata:
  name: preprocessing-service
  namespace: windoutput
  labels:
    app: preprocessing-service
  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: preprocessing-service
  template:
    metadata:
      labels:
        app: preprocessing-service
    spec:
      containers:
      - name: preprocessing-service
        image: amitgupta2533/preprocessing-service:v0.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8001
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: preprocessing-service
  namespace: windoutput
  labels:
    app: preprocessing-service
  
spec:
  type: LoadBalancer
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: preprocessing-service
