apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-pipeline-sa
  namespace: env-qa   # Service account created in the 'env-qa' namespace
automountServiceAccountToken: false
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-sa-secret
  annotations:
    kubernetes.io/service-account.name: "azure-pipeline-sa"
  namespace: env-qa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-sa-role
  namespace: env-qa
rules:
- apiGroups: [""]
  resources: ["pods", "services", "deployments", "secrets"]  # Added "secrets"
  verbs: ["create", "get", "list", "delete", "update"]       # Adjust based on requirements
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-rolebinding
  namespace: env-qa
subjects:
- kind: ServiceAccount
  name: azure-pipeline-sa
  namespace: env-qa
roleRef:
  kind: Role
  name: deploy-sa-role
  apiGroup: rbac.authorization.k8s.io

