apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-pipeline-sa
  namespace: env-qa
automountServiceAccountToken: true
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-sa-secret
  annotations:
    kubernetes.io/service-account.name: "azure-pipeline-sa"
  namespace: env-qa
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deploy-sa-role
  namespace: env-qa
rules:
  # Permissions for Deployments
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/status", "replicasets"]
    verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
  # Permissions for Pods
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete"]
  # Permissions for Services
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
  # Permissions for ConfigMaps (if used by Helm charts)
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
  # Permissions for Secrets
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "watch", "update", "delete", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-rolebinding
  namespace: env-qa
subjects:
  - kind: ServiceAccount
    name: azure-pipeline-sa
    namespace: env-qa
roleRef:
  kind: Role
  name: deploy-sa-role
  apiGroup: rbac.authorization.k8s.io
