apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}
  labels:
    app: {{ .Values.job.labels.app | default "training-job" }}
spec:
  template:
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: {{ .Values.container.image }}
        imagePullPolicy: {{ .Values.container.imagePullPolicy | default "Always" }}
        env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.awsSecretName }}
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.env.awsSecretName }}
              key: AWS_SECRET_ACCESS_KEY
        - name: AWS_DEFAULT_REGION
          value: {{ .Values.env.awsRegion | default "us-east-1" }}
        - name: MLFLOW_TRACKING_URI
          value: {{ .Values.env.mlflowTrackingUri }}
        ports:
        - containerPort: {{ .Values.container.port | default 8080 }}
          name: {{ .Values.container.portName | default "http" }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory | default "512Mi" }}
            cpu: {{ .Values.resources.requests.cpu | default "500m" }}
          limits:
            memory: {{ .Values.resources.limits.memory | default "1Gi" }}
            cpu: {{ .Values.resources.limits.cpu | default "1" }}
      restartPolicy: {{ .Values.restartPolicy | default "Never" }}
