apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-connection-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aws-connection-test
  template:
    metadata:
      labels:
        app: aws-connection-test
    spec:
      containers:
      - name: aws-cli
        image: amazon/aws-cli:latest
        command:
          - "/bin/sh"
          - "-c"
          - "aws s3 ls s3://mlops-aws-windoutput"
        env:
        - name: AWS_DEFAULT_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials-dev1
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials-dev1
              key: AWS_SECRET_ACCESS_KEY
