trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - bugfix/*
  # Disable automatic path-based trigger as this will be parameterized
  paths:
    include:
      - inference

pool:
  vmImage: 'ubuntu-latest' # Define the build agent

# Define a parameter for directory path
parameters:
  - name: directoryPath
    displayName: Directory Path
    type: string
    default: "inference"  # Default value if none is provided

# Define a parameter for directory path
parameters:
  - name: directoryPath
    displayName: Directory Path
    type: string
    default: "inference"  # Default value if none is provided

stages:
  - stage: Validator
    displayName: Validate Build Prerequisites
    jobs:
      - job: validate_files_and_directories
        displayName: Validate Required Files and Directories
        steps:
          - checkout: self
          - script: |
              # Parameterized directory path
              DIR_PATH="${{ parameters.directoryPath }}"

              echo "Validating directory: $DIR_PATH"

              # Check if the directory exists
              if [ ! -d "$DIR_PATH" ]; then
                echo "Error: Directory '$DIR_PATH' is missing!" && exit 1
              else
                echo "Directory '$DIR_PATH' is present."
              fi

              echo "Validation successful: Directory '$DIR_PATH' is present."
            displayName: Validate Parameterized Directory
