trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - bugfix/*
  # Disable automatic path-based trigger as this will be parameterized
  paths:
    include:
      - preprocessing

pool:
  vmImage: 'ubuntu-latest' # Define the build agent

variables:
  - group: DockerCredentials


# Define a parameter for directory path
parameters:
  - name: directoryPath
    displayName: Directory Path
    type: string
    default: "preprocessing"  # Default value if none is provided
  - name: version
    displayName: Update Version to
    type: string
    default: "1.0.0"  # Default value if none is provided

resources:
  repositories:
  - repository: HelmCharts # The name used to reference this repository in the checkout step
    type: github
    endpoint: ado-terraform-token
    name: Analyst-Amit/helm-charts

stages:
  # - stage: Validator
  #   displayName: Validate Build Prerequisites
  #   jobs:
  #     - job: validate_files_and_directories
  #       displayName: Validate Required Files and Directories
  #       steps:
  #         - checkout: self
  #         - script: |
  #             # Parameterized directory path
  #             DIR_PATH="${{ parameters.directoryPath }}"

  #             echo "Validating directory: $DIR_PATH"

  #             # Check if the directory exists
  #             if [ ! -d "$DIR_PATH" ]; then
  #               echo "Error: Directory '$DIR_PATH' is missing!" && exit 1
  #             else
  #               echo "Directory '$DIR_PATH' is present."
  #             fi

  #             echo "Validation successful: Directory '$DIR_PATH' is present."
  #           displayName: Validate Parameterized Directory

  # - stage: push_pre_processing_image
  #   displayName: Deploy to Production
  #   jobs:
  #     - job: docker_build_and_push_prod
  #       displayName: Build Docker Image and Push to Docker Hub
  #       steps:
  #         - checkout: self
  #         - script: echo "DOCKER_USERNAME is- $(DOCKER_USERNAME)"
  #           displayName: Print DOCKER_USERNAME
  #         - script: ls -la ${{ parameters.directoryPath }}
  #           displayName: List Files in the Directory
  #         - task: Docker@2
  #           displayName: Build and Push Docker Image
  #           inputs:
  #             containerRegistry: docker-hub-connection
  #             repository: $(DOCKER_USERNAME)/preprocessing
  #             command: buildAndPush
  #             Dockerfile: ${{ parameters.directoryPath }}/Dockerfile
  #             tags: |
  #               latest
  #               $(Build.SourceBranchName)
  - stage: PushFileToAnotherRepo
    displayName: Push File to Another GitHub Repository
    jobs:
      - job: create_helm_pkg
        displayName: Push File Job
        steps:
          - checkout: HelmCharts
            persistCredentials: true

          - checkout: self
            displayName: Checking out complete Repo

          - script: |
              yq eval '.version = "${{ parameters.version }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/Chart.yaml
              yq eval '.appVersion = "${{ parameters.version }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/Chart.yaml
              cat mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/Chart.yaml
            displayName: "Updated ${{ parameters.directoryPath }} Chart.yaml"

          - task: HelmInstaller@1
            displayName: Helm installer
            inputs: 
              helmVersionToInstall: 3.16.3
          
          - script: |
              helm package mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service --destination mlops-windoutput-helm/helm/packages
              echo "Helm chart packaged successfully in 'mlops-windoutput-helm/helm/packages'"
            displayName: "Updated and Packaged ${{ parameters.directoryPath }} Helm Chart"

          - script: |
              # Verify the packaged files
              echo "Contents of 'packages' directory:"
              ls -la mlops-windoutput-helm/helm/packages
              echo "Contents of 'helm' directory:"
              ls -la mlops-windoutput-helm/helm
              ls -la
              echo "Contents of main directory"
            displayName: "List Packaged Files"


          - script: |
              cd helm-charts
              git status
              git config --global user.email pipeline@demo.com
              git config --global user.name "Pipeline"
              git checkout -b main
              # Check if the source file exists
              if [ -f mlops-windoutput-helm/helm/packages/preprocessing-service-3.0.1.tgz ]; then
                  echo "File found. Copying to the target directory..."
                  mkdir -p helm-charts/preprocessing
                  cp mlops-windoutput-helm/helm/packages/preprocessing-service-3.0.1.tgz helm-charts/preprocessing/
                  echo "File successfully copied to helm-charts/preprocessing/"
              else
                  echo "File preprocessing-service-3.0.1.tgz not found in mlops-windoutput-helm/helm/packages/"
                  exit 1
              fi
              git add -A
              git commit -m "Add latest preprocessing file"
              echo "Pushing changes to the main branch..."
              git push -u origin main
            displayName: Create, Commit, and Push



