trigger:
  batch: true
  branches:
    include:
      - main
      - feature/*
      - bugfix/*
  # Disable automatic path-based trigger as this will be parameterized
  # paths:
  #   include:
  #     - preprocessing

pool:
  vmImage: 'ubuntu-latest' # Define the build agent

variables:
  - group: DockerCredentials


# Define a parameter for directory path
parameters:
  - name: directoryPath
    displayName: Directory Path
    type: string
    default: "preprocessing"  # Default value if none is provided
  - name: version
    displayName: Update Version to
    type: string
    default: "1.0.0"  # Default value if none is provided

resources:
  repositories:
  - repository: HelmCharts # The name used to reference this repository in the checkout step
    type: github
    endpoint: ado-terraform-token
    name: Analyst-Amit/helm-charts

stages:
  # - stage: Validator
  #   displayName: Validate Build Prerequisites
  #   jobs:
  #     - job: validate_files_and_directories
  #       displayName: Validate Required Files and Directories
  #       steps:
  #         - checkout: self
  #         - script: |
  #             # Parameterized directory path
  #             DIR_PATH="${{ parameters.directoryPath }}"

  #             echo "Validating directory: $DIR_PATH"

  #             # Check if the directory exists
  #             if [ ! -d "$DIR_PATH" ]; then
  #               echo "Error: Directory '$DIR_PATH' is missing!" && exit 1
  #             else
  #               echo "Directory '$DIR_PATH' is present."
  #             fi

  #             echo "Validation successful: Directory '$DIR_PATH' is present."
  #           displayName: Validate Parameterized Directory

#   - stage: building_${{ parameters.directoryPath }}_image
#     jobs:
#       - job: build_and_tag_image
#         displayName: Build Docker Image and Push to Docker Hub
#         steps:
#           - checkout: self
#           - script: echo "DOCKER_USERNAME is- $(DOCKER_USERNAME)"
#             displayName: Print DOCKER_USERNAME
#           - script: ls -la ${{ parameters.directoryPath }}
#             displayName: List Files in the Directory
#           - task: Docker@2
#             displayName: Build and Push Docker Image
#             inputs:
#               containerRegistry: docker-hub-connection
#               repository: $(DOCKER_USERNAME)/preprocessing
#               command: buildAndPush
#               Dockerfile: ${{ parameters.directoryPath }}/Dockerfile
#               tags: |
#                 latest
#                 ${{ parameters.version }}
# #                $(Build.SourceBranchName)

#   - stage: PackageHelmChart
#     jobs:
#       - job: create_helm_pkg
#         displayName: Package helm charts and artifact.
#         steps:
#           - checkout: HelmCharts
#             persistCredentials: true

#           - checkout: self
#             displayName: Checking out complete Repo

#           - script: |
#               yq eval '.version = "${{ parameters.version }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/Chart.yaml
#               yq eval '.appVersion = "${{ parameters.version }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/Chart.yaml
#               cat mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/Chart.yaml
#             displayName: "Updated ${{ parameters.directoryPath }} Chart.yaml"

#           - script: |
#               yq eval '.image.repository = "amitgupta2533/${{ parameters.directoryPath }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/values.yaml
#               yq eval '.image.tag = "${{ parameters.version }}"' -i mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/values.yaml
#               cat mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service/values.yaml
#             displayName: "Updated ${{ parameters.directoryPath }} values.yaml"

#           - task: HelmInstaller@1
#             displayName: Helm installer
#             inputs: 
#               helmVersionToInstall: 3.16.3
          
#           - script: |
#               helm package mlops-windoutput-helm/helm/${{ parameters.directoryPath }}-service --destination mlops-windoutput-helm/helm/packages
#               echo "Helm chart packaged successfully in 'mlops-windoutput-helm/helm/packages'"
#             displayName: "Updated and Packaged ${{ parameters.directoryPath }} Helm Chart"

#           - task: PublishBuildArtifacts@1
#             inputs:
#               pathToPublish: mlops-windoutput-helm/helm/packages
#               artifactName: helm-chart-artifact
#               publishLocation: Container

#   - stage: PushFileToChartsRepo
#     jobs:
#       - job: push_file
#         steps:
#           - checkout: HelmCharts
#             persistCredentials: true
#           - checkout: self
#             displayName: Checking out complete Repo
            
#           - task: DownloadBuildArtifacts@0
#             inputs:
#               buildType: 'current'
#               downloadType: 'specific'
#               artifactName: 'helm-chart-artifact'
#               downloadPath: '$(Pipeline.Workspace)/helm-chart'
          
#           - task: HelmInstaller@1
#             displayName: Helm installer
#             inputs: 
#               helmVersionToInstall: 3.16.3

#           - script: |
#               cd helm-charts
#               git status
#               git config --global user.email pipeline@demo.com
#               git config --global user.name "Pipeline"
#               git checkout main || git checkout -b main
              
#               # Check if the artifact file exists
#               if [ -f "$(Pipeline.Workspace)/helm-chart/helm-chart-artifact/${{ parameters.directoryPath }}-service-${{ parameters.version }}.tgz" ]; then
#                   echo "File found. Copying to the target directory..."
#                   mkdir -p ${{ parameters.directoryPath }}
#                   cp "$(Pipeline.Workspace)/helm-chart/helm-chart-artifact/${{ parameters.directoryPath }}-service-${{ parameters.version }}.tgz" ${{ parameters.directoryPath }}/
#                   echo "File successfully copied"
#               else
#                   echo "File ${{ parameters.directoryPath }}-service-${{ parameters.version }}.tgz not found in artifact"
#                   exit 1
#               fi
#               helm repo index ${{ parameters.directoryPath }} --url https://analyst-amit.github.io/helm-charts/${{ parameters.directoryPath }}
#               git add -A
#               git commit -m "Added latest ${{ parameters.directoryPath }} file"
#               git push -u origin main
#             displayName: Create, Commit, and Push
  
  - stage: deployment_QA
    jobs:
      - job: deploy_qa
        steps:
          # Checkout code from the repository
          - checkout: HelmCharts # Or use `HelmCharts` if it's an external repository
            persistCredentials: true

          - script: |
              echo "Checking for Helm chart files..."
              ls preprocessing
            displayName: "Verify Helm Chart Files"

          # Deploy with Helm
          - task: HelmDeploy@1
            displayName: Deploy Preprocessing Service with Helm
            inputs:
              # Kubernetes Cluster Configuration
              connectionType: 'Kubernetes Service Connection' # Connect to Kubernetes.
              kubernetesServiceConnection: azure-pipeline-sa # Service connection for authentication.
              namespace: env-qa # Target namespace for deployment.

              # Helm Command and Chart Details
              command: 'upgrade' # Upgrade the release or install if not found.
              chartType: filepath  # Use the local chart from your GitHub repository.
              chartPath: 'preprocessing/preprocessing-service-3.0.5.tgz' # Path to the chart file.
              releaseName: 'preprocessing-service' # Helm release name for deployment.
              install: true # Allows installation if the release is not found.








