apiVersion: apps/v1
kind: Deployment
metadata:
  name: inference-service
  labels:
    app: inference-service
spec:
  replicas: 2  # Number of pod replicas
  selector:
    matchLabels:
      app: inference-service
  template:
    metadata:
      labels:
        app: inference-service
    spec:
      containers:
      - name: inference-service
        image: amitgupta2533/inference-service:v0.0.1
        imagePullPolicy: Always
        env:
        - name: MLFLOW_TRACKING_URI
          value: http://130.211.120.30:5000  # Add your MLflow Tracking URI
        ports:
        - containerPort: 8000
          name: http
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: inference-service
  labels:
    app: inference-service
spec:
  selector:
    app: inference-service  # Matches the label in Deployment
  ports:
    - protocol: TCP
      port: 80              # Exposed port for external access
      targetPort: 8000      # Port the app listens on in the container
  type: LoadBalancer         # Use LoadBalancer for external access (can also use NodePort or ClusterIP)
